public enum TokenType {
    YILDIZ, KEHANET, RETRO, ILERLEME, DOLUNAY, FAL,
    TUVAL_AC, IZ_BIRAK, KOSE_DON,
    IDENTIFIER, NUMBER, STRING, BOOLEAN,
    ASSIGN, EQUALS, PLUS, MINUS,
    LPAREN, RPAREN, LBRACE, RBRACE, SEMICOLON, COMMA,
    EOF
}